# Generated by Django 4.2.1 on 2023-05-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
