# Generated by Django 4.2.1 on 2023-05-15 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_at",
        ),
    ]
