# Generated by Django 4.2.1 on 2023-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
