# Generated by Django 4.2.1 on 2023-05-26 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_populate_created_at"),
        ("product", "0003_populate_slug_value"),
    ]

    operations = []
