# Generated by Django 4.2.1 on 2023-05-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_created_product_created_at'),
        ('product', '0004_alter_product_slug'),
        ('product', '0004_populate_slug_value'),
    ]

    operations = [
    ]
