# Generated by Django 4.2.1 on 2023-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_populate_slug_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
