# Generated by Django 4.2.1 on 2023-05-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_populate_slug_value"),
        ("product", "0004_alter_product_created_at"),
    ]

    operations = []
