# Generated by Django 4.2.1 on 2023-05-26 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_slug"),
        ("product", "0005_merge_20230526_2039"),
        ("product", "0005_remove_product_created_alter_product_created_at"),
    ]

    operations = []
