# Generated by Django 4.2.1 on 2023-05-26 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_is_published"),
        ("product", "0006_merge_20230526_2058"),
    ]

    operations = []
