# Generated by Django 4.2.1 on 2023-05-27 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_created_from_db"),
        ("product", "0007_merge_20230526_2121"),
    ]

    operations = []
